services:
  # Metabase application database (separate Postgres)
  pg-metabase:
    image: postgres:15
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase_pass
    volumes:
      - ./pg_metabase/data:/var/lib/postgresql/data
    networks:
      - metanet

  # Metabase
  metabase:
    image: metabase/metabase:latest
    ports:
      - "9090:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase_pass
      MB_DB_HOST: pg-metabase
    depends_on:
      - pg-metabase
      - trino
    networks:
      - metanet

  # Trino
  trino:
    image: trinodb/trino:latest
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
    networks:
      - metanet

  # Postgres datasource
  postgres-ds:
    image: postgres:15
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: app_pass
    ports:
      - 54326:5432
    volumes:
      - ./pg_ds/data:/var/lib/postgresql/data
      - ./pg_ds/init:/docker-entrypoint-initdb.d
    networks:
      - metanet

  # MSSQL datasource
  mssql-ds:
    image: mcr.microsoft.com/azure-sql-edge
    # image: mcr.microsoft.com/mssql/server:2017-latest
    # user: "10001:0"
    user: root
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer" # 👈 Important: run as Developer Edition
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - ./mssql_ds/mssql-data:/var/opt/mssql
    networks:
      - metanet

# volumes:
#   metabase_db_data:
#   postgres_ds_data:
#   mssql_ds_data:

networks:
  metanet:
